name: Build and Push Docker Image

on:
  push:
    branches:
      - xfers
  pull_request:

env:
  OTP_VERSION: '24.3.4.1'
  ELIXIR_VERSION: '1.13.4'

jobs:
  push_to_registry:
    name: Push Docker image to Docker Hub
    runs-on: ubuntu-latest
    outputs:
      release-version: ${{ steps.output-step.outputs.release-version }}
      short-sha: ${{ steps.output-step.outputs.short-sha }}
    steps:
      - name: Check out the repo
        uses: actions/checkout@v3

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v4
        with:
          images: ${{ secrets.DOCKER_USERNAME }}/blockscout

      - name: Add Pull Request SHORT_SHA
        if: github.event_name == 'pull_request'
        run: echo "SHORT_SHA=`echo ${{ github.event.pull_request.head.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Add Push SHORT_SHA
        if: github.event_name == 'push'
        run: echo "SHORT_SHA=`echo ${{ github.sha }} | cut -c1-7`" >> $GITHUB_ENV

      - name: Set Sha Tag
        id: set-sha-tags
        shell: bash
        run: |
          echo "TAGS=${{ secrets.DOCKER_USERNAME }}/blockscout:${{ env.SHORT_SHA }}" >> $GITHUB_ENV

      - name: Set Latest Tag
        id: set-latest-tags
        if: github.ref == 'refs/heads/xfers'
        shell: bash
        run: |
          echo "TAGS=${{ env.TAGS }},${{ secrets.DOCKER_USERNAME }}/blockscout:latest" >> $GITHUB_ENV

      - name: Build and push Docker image
        uses: docker/build-push-action@v3
        with:
          context: .
          file: ./Dockerfile
          pull: true
          push: true
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/blockscout:buildcache
          cache-to: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/blockscout:buildcache,mode=max
          tags: ${{ env.TAGS }}
          build-args: |
            CACHE_EXCHANGE_RATES_PERIOD=
            DISABLE_READ_API=false
            API_PATH=
            NETWORK_PATH=
            DISABLE_WEBAPP=false
            DISABLE_WRITE_API=false
            CACHE_ENABLE_TOTAL_GAS_USAGE_COUNTER=
            WOBSERVER_ENABLED=false
            ADMIN_PANEL_ENABLED=false
            CACHE_ADDRESS_WITH_BALANCES_UPDATE_INTERVAL=
            DISABLE_BRIDGE_MARKET_CAP_UPDATER=false
            CACHE_BRIDGE_MARKET_CAP_UPDATE_INTERVAL=
            SOCKET_ROOT=
            CHAIN_ID=
            JSON_RPC=
            COIN_NAME=
            SUBNETWORK=